spring.application.name=recon
spring.datasource.url=jdbc:postgresql://localhost:5432/platinum
spring.datasource.username=postgres
spring.datasource.password=Lennon1968#&
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=shutdown